server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: root
    password: root@123
    driver-class-name: org.postgresql.Driver
  application:
      name:USER-SERVICE


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.netflix.discovery: DEBUG

eureka:
  instance:
    prefer-ip-address: true


  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
