server:
  port: 8082
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG


#  instance:
#    hostname: localhost
#    prefer-ip-address: true

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true