server:
  port: 8761

spring:
  application:
    name: service-registry
  profiles:
    active: default

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: DEBUG



