server:
  port: 8083
spring:
  application:
    name: RATING-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservices
      database: microservices
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
